# Generated by Django 6.0.3 on 2026-09-30 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=255)),
                ('row_number', models.PositiveIntegerField()),
                ('original_data', models.JSONField()),
                ('response', models.CharField(choices=[('no_response', 'No Response'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('callback', 'Callback'), ('converted', 'Converted')], default='no_response', max_length=32)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='customers.dataset')),
            ],
            options={
                'ordering': ['dataset_id', 'sheet_name', 'row_number'],
                'constraints': [models.UniqueConstraint(fields=('dataset', 'sheet_name', 'row_number'), name='unique_dataset_sheet_row')],
            },
        ),
        migrations.CreateModel(
            name='DatasetColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('field_key', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='customers.dataset')),
            ],
            options={
                'ordering': ['sheet_name', 'order'],
                'constraints': [models.UniqueConstraint(fields=('dataset', 'sheet_name', 'field_key'), name='unique_dataset_sheet_column_key')],
            },
        ),
    ]
