# Generated by Django 6.0.8 on 2026-10-01 06:35

import customers.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_visit_customer_manualclient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=customers.models.visit_image_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='customers.visit')),
            ],
            options={
                'ordering': ['uploaded_at', 'id'],
            },
        ),
    ]
