# Generated by Codex on 2026-10-05

from django.db import migrations, models


def collapse_dataset_targets_to_month(apps, schema_editor):
    SalesTarget = apps.get_model("customers", "SalesTarget")

    grouped = {}
    for target in SalesTarget.objects.order_by("user_id", "month", "id"):
        grouped.setdefault((target.user_id, target.month), []).append(target)

    for targets in grouped.values():
        keeper = targets[0]
        keeper.target = max(target.target for target in targets)
        keeper.dataset_id = None
        keeper.save(update_fields=["target", "dataset"])
        for duplicate in targets[1:]:
            duplicate.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0010_assignedtask"),
    ]

    operations = [
        migrations.RunPython(collapse_dataset_targets_to_month, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="salestarget",
            name="unique_sales_target_user_dataset",
        ),
        migrations.AlterModelOptions(
            name="salestarget",
            options={"ordering": ["-month", "user__username"]},
        ),
        migrations.AddConstraint(
            model_name="salestarget",
            constraint=models.UniqueConstraint(
                fields=("user", "month"),
                name="unique_sales_target_user_month",
            ),
        ),
    ]
